name: bs_overlay_loader
description: Overlay simple progress loader to screen.
version: 0.0.1
author: bebe<leebebe0612@gmail.com>
homepage: https://github.com/bebe0612/bs_overlay_loader

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

